[#title]
= Connecting Kafka topics to a Quarkus application

[#description]
In this tutorial, you will set up a Kafka instance and create topics to be used with a Quarkus application

[#introduction]
We will be using Apache Kafka, an open-source distributed event streaming platform used by thousands of companies for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications.
    
You can learn more about Apache Kafka by visiting [https://kafka.apache.org/](https://kafka.apache.org/).
    
Quarkus is an open source, Kubernetes-native Java framework that allows developers to optimize container-native applications for peak performance.
    
You can learn more about Quarkus by visiting [https://quarkus.io/](https://quarkus.io/).

.Prerequisites
* Red Hat OpenShift
* Red Hat Streams for Apache Kafka

[#task-1]
== Kafka

In this step, you will create a Kafka instance and connect topics to them.

Click on the *Launch RHOSAK* button to launch _Red Hat OpenShift Streams for Apache Kafka_. Once launched, follow the quick start within it.

https://cloud.redhat.com/beta/application-services/overview?quickstart=getting-started[Launch RHOSAK,role="tutorial-external"]

.Verification
. Did you create a Kafka instance?
. Did you create a Kafka topic?

[#task-2]
== Connecting Kafka to OpenShift

Now that you've set up a kafka with topics, you'll be connecting that to an application that you create on OpenShift.

Click on the *Launch OpenShift* button to launch _Red Hat OpenShift Streams for Apache Kafka_. Once launched, follow the quick start within it.

https://console-openshift-console.apps.sandbox-m2.ll9k.p1.openshiftapps.com/topology/ns/jschuler-kafka-devexp-dev/graph?quickstart=quarkus[Launch OpenShift,role="tutorial-external"]

.Verification
. Did you create a quarkus app?
. Did you connect a Kafka topic to it?

[#conclusion]
Congratulations! You successfully completed the quick start.
