:walkthrough: Demo

[id='demo']
= {walkthrough}

This solution pattern will walk you through the creation of a kafka stream, and will also have you create a topic and connect it to the stream.

This Solution Pattern consists of the following components:

* Red Hat OpenShift Streams for Apache Kafka (RHOSAK)
* RHOSAK CLI


[type=walkthroughResource,serviceName=rhosak]
.Red Hat OpenShift Streams for Apache Kafka (RHOSAK)
****
* link:https://cloud.redhat.com[Console, window="_blank"]
****

[type=walkthroughResource,serviceName=rhosak-cli]
.RHOSAK CLI
****
* link:https://cloud.redhat.com[Console, window="_blank"]
****


[time=5]

[id='creating-kafka']


:sectnums:


==  Creating a Kafka instance

For this task, you will create a Kafka instance.

. Choose the following as the instance name:
+
[subs="attributes+", role="clipboard"]
----
kafka-test
----
. Copy the instance name and launch the app in the next step. Follow the quick start steps within the app to create a kafka instance.
. Open the [.app-launch-control]#Kafka control plane#.

[type=verification]
Were you able to create a kafka instance with the name `+kafka-test+`?

[type=verificationFail]
Verify that you followed each step in the procedure above. If you are still having issues, contact your administrator.


[time=5]
== Creating a topic

For this task, you will create a kafka topic.

. Choose the following as the topic name:
+
[subs="attributes+", role="clipboard"]
----
topic-test
----
. Copy the topic name and launch the app in the next step. Follow the quick start steps within the app to create a kafka topic.
. Open the [.app-launch-data]#Kafka data plane#.

[type=verification]
Were you able to create a kafka topic with the name `+topic-test+`?

[type=verificationFail]
Verify that you followed each step in the procedure above. If you are still having issues, contact your administrator.


[time=5]
== Connecting to a topic

For this task, you will connect a topic to the kafka stream.

=== Update Quarkus Configuration File

Open your favourate editor and update the
link:src/main/resources/application.properties[application.properties]
with the following content

[source,properties]
----
kafka.bootstrap.servers=<kafka-bootstrap-server>:443
sasl.mechanism=PLAIN
security.protocol=SASL_SSL

sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
  username="<USER>" \
  password="<PASSWORD>";
----

____
NOTE: `<kafka-bootstrap-server>` is the bootstrap server url
____

Save, now you are ready to start the application.

=== Start the application

Run the application in dev mode with.

[source,bash]
----
./mvnw quarkus:dev
----

Then, open your browser to `http://localhost:8080/prices.html`, and you
should see a fluctuating price.

=== Anatomy

In addition to the `prices.html` page, the application is composed by 3
components:

* `PriceGenerator` - a bean generating random price. They are sent to a
Kafka topic
* `PriceConverter` - on the consuming side, the `PriceConverter`
receives the Kafka message and convert the price. The result is sent to
an in-memory stream of data
* `PriceResource` - the `PriceResource` retrieves the in-memory stream
of data in which the converted prices are sent and send these prices to
the browser using Server-Sent Events.

The interaction with Kafka is managed by MicroProfile Reactive
Messaging. The configuration is located in the
link:src/main/resources/application.properties[application
configuration].

=== Running in JVM mode

Package the application with

[source,bash]
----
./mvnw clean package
----

and run with

[source,bash]
----
java -jar target/mas-kafka-1.0-SNAPSHOT-runner.jar
----

=== Running in native

You can compile the application into a native binary using:

[source,bash]
----
./mvnw clean install -Pnative
----

and run with:

[source,bash]
----
./target/mas-kafka-1.0-SNAPSHOT-runner
----

[type=verification]
Did you connect the topic to the kafka stream?

[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.
