////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////


:community:
:imagesdir: ./images
:product-long: bf2fc6cc711aee1a0c2a
:product: bf2
// Placeholder URL, when we get a HOST UI for the service we can put it here properly
:service_url: https://localhost:1234/
:signup_link: https://localhost:1234/
// Other upstream project names
:quarkus: Quarkus
:quarkus_url: https://quarkus.io/
:samples_git_repo: https://github.com/bf2fc6cc711aee1a0c2a/guides

////
END GENERATED ATTRIBUTES
////

[id="chap-using-quarkus"]
= Using {quarkus} with Kafka instances in {product-long}
ifdef::context[:parent-context: {context}]
:context: using-quarkus

// Purpose statement for the assembly
[role="_abstract"]
As a developer of applications and services, you can connect {quarkus} to {product-long}. {quarkus} is a Kubernetes Native Java stack tailored for OpenJDK HotSpot and GraalVM, crafted from the best of breed Java libraries and standards.

.Prerequisites
ifndef::community[]
* You have a Red Hat account.
endif::[]
* You have a access to {product-long}. For more information about signing up, see link:{signup_link}[].
* You have a running Kafka instance in {product}.
* You have link:https://github.com/git-guides/[git] installed
* You have an link:https://en.wikipedia.org/wiki/Comparison_of_integrated_development_environments#Java[IDE] like link:https://www.jetbrains.com/idea/download/[IntelliJ IDEA], link:https://www.eclipse.org/downloads/[Eclipse], link:https://code.visualstudio.com/Download[VSCode] or even link:https://spacevim.org/use-vim-as-a-java-ide/[Vim] or link:http://spacemacs.org/[Emacs]!
* You need a link:https://adoptopenjdk.net/[JDK 8 or 11+] (any distribution)
* You need link:https://maven.apache.org/[Apache Maven 3.6.2+]

// Condition out QS-only content so that it doesn't appear in docs.
// All QS anchor IDs must be in this alternate anchor ID format `[#anchor-id]` because the ascii splitter relies on the other format `[id="anchor-id"]` to generate module files.
ifdef::qs[]
[#description]
Learn how to use Quarkus to produce messages to and consume messages from a Kafka instance in {product-long}.

[#introduction]
Welcome to the {product-long} Quarkus quick start. In this quick start, you'll learn how to use link:{quarkus_url}[{quarkus}] to produce messages to and consume messages from your Kafka instances in {product-long}.
endif::[]

[id="prereq-fields"]
== Gather required info

Howdy, this is some text

[.tutorial-input]
====
component:: text-field
name:: asd-login
label:: asd Your login name
description:: asd Fill in your login name
isRequired:: true
helperText:: asd You can find this information on cloud.redhat.com
validate::
    type::: required
====

This is more text

[id="proc-getting-the-sample-code_{context}"]
== Getting the same code

{quarkus} is a Kubernetes Native Java stack tailored for OpenJDK HotSpot and GraalVM, crafted from the best of breed Java libraries and standards. Applications built for Quarkus can produce messages to and consume messages to {product} using MicroProfile Reactive Messaging.

In order to follow this quick start get the sample from GitHub and open it in your IDE.

https://cloud.redhat.com[Red Hat^,role="tutorial-external"]

ifdef::qs[]
.Verification
* You have the quarkus project imported into your IDE and the IDE has configured the project with the needed Java libraries from the Maven `pom.xml`.
endif::[]

[id="proc-configuring-quarkus_{context}"]
== Configuring your {quarkus} application to connect to a Kafka instance

To enable your Quarkus application to access a Kafka instance, you must configure the connection using the bootstrap server endpoint and the generated credentials for your {product} service account. For Quarkus, you can configure connection information by using the `application.properties` configuration file. This example sets environment variables and then references them in `application.properties`.

For more information about Quarkus configuration options for using Kafka with MicroProfile Reactive Messaging, see https://quarkus.io/guides/kafka[the guide] in the {quarkus} documentation.

.Prerequisites
* You have the bootstrap server endpoint (external server endpoint) and the generated credentials for your service account. You retrieved this information previously for the Kafka instance in {product} by selecting the options menu (three vertical dots), clicking *Connect to instance*, and generating the service account.

[id="proc-create-prices-topic_{context}"]
== Create the prices topic

This example uses a topic called `prices`

.Prerequisites
* You have created a Kafka instance in the {product} web console and the instance is in *Ready* state.

.Verification
ifdef::qs[]
* Is the new Kafka topic `prices` listed in the topics table?
endif::[]
ifndef::qs[]
* Verify that the new Kafka topic `prices` is listed in the topics table.
endif::[]


[id="proc-running-the-quarkus-application_{context}"]
== Running the {quarkus} application

This example is a small Quarkus application. It has three application scoped beans, one of which generates a random number between 0 and 100 and produces it to a Kafka topic, another that consumes it from the Kafka topic, and a final bean that exposes it as a REST UI (using Server Sent events).

.Prerequisites
* You have a running Kafka instance in {product}.
* You have link:https://github.com/git-guides/[git] installed
* You have an link:https://en.wikipedia.org/wiki/Comparison_of_integrated_development_environments#Java[IDE] like link:https://www.jetbrains.com/idea/download/[IntelliJ IDEA], link:https://www.eclipse.org/downloads/[Eclipse], link:https://code.visualstudio.com/Download[VSCode] or even link:https://spacevim.org/use-vim-as-a-java-ide/[Vim] or link:http://spacemacs.org/[Emacs]!
* You need a link:https://adoptopenjdk.net/[JDK 8 (8u262-b10 or later) or 11+] (any distribution)
* You need link:https://maven.apache.org/[Apache Maven 3.6.2+]

.Verification
. Check that there are no error messages being produced by {quarkus}
. Visit link:http://localhost:8080/prices.html[] and check that the Last price updates
ifdef::qs[]

[#conclusion]
Congratulations! You successfully completed the {product} {quarkus} quick start, and are now ready to add {product} to your own {quarkus} application.
endif::[]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
